---

- name: Start apache httpd
  systemd:
    name: apache2
    enabled: true
    state: restarted
  listen: restart apache
  notify: verify apache

- name: Verify webpage is up and redirecting
  uri:
    url: "http://{{ ansible_facts.default_ipv4.address }}"
    return_content: true
    validate_certs: false
  register: webserver_status
  until: webserver_status.content_type is search('html', ignorecase=true)
  retries: 12
  delay: 5
  failed_when: webserver_status.redirected == false or
               webserver_status.status != 200 or
               webserver_status.url is not search('https')
  listen: verify apache

...