---

# - name: Create apache groups
#   group:
#     name: "{{ apache_group }}"
#     state: present

# - name: Create apache default user
#   user:
#     name: "{{ apache_user }}"
#     group: "{{ apache_group }}"

- name: Install apache httpd
  apt:
    name: apache2
    update_cache: true
    state: present
  notify: restart apache

...