---

- name: Install apache httpd
  apt:
    name: apache2
    update_cache: true
    state: present
  notify: restart apache

- name: Set permissions on apache dir
  file:
    path: "{{ apache_website_dir }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: u=rwX,g=rX,o=
    recurse: true
    state: directory

...