---

- name: Template in nginx conf
  template:
    src: nginx-default.conf.j2
    dest: "{{ nginx_site_config_dir }}/nginx-default.conf"
    mode: '0644'
  notify: reload nginx

- name: Enable new site config
  file:
    src: "{{ nginx_site_config_dir }}/nginx-default.conf"
    dest: "{{ nginx_site_enabled_dir }}/nginx-default.conf"
    state: link
  notify: reload nginx

- name: Test nginx config
  command: nginx -t
  changed_when: false

...